In [ ]:
import pandas as pd
data_df = pd.read_csv('/content/INCART 2-lead Arrhythmia Database.csv')
print(data_df.shape)
data_df.head()

(21490, 34)


record type  0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak  \
0    I01    N       163        165  0.069610 -0.083281  0.614133 -0.392761   
1    I01    N       165        166 -0.097030  0.597254 -0.078704 -0.078704   
2    I01    N       166        102  0.109399  0.680528 -0.010649 -0.010649   
3    I01  VEB       102        231  0.176376  0.256431 -0.101098 -0.707525   
4    I01    N       231        165  0.585577  0.607461 -0.083499 -0.083499   

    0_qPeak  0_qrs_interval  ...   1_qPeak  1_qrs_interval  1_pq_interval  \
0  0.047159              15  ... -0.023370              14              3   
1 -0.137781               3  ...  0.081637              15              5   
2 -0.720620               6  ... -0.148539              33             13   
3 -0.101098               4  ...  0.046898              21              9   
4 -0.167858               3  ... -0.112552              32              5   

   1_qt_interval  1_st_interval  1_qrs_morph0  1_qrs_morph1  1_qrs_morph2  \
0             23              6     -0.023370     -0.011650      0.082608   
1             27              7      0.081637      0.102992      0.191225   
2             52              6     -0.148539     -0.060620      0.081080   
3             34              4      0.046898      0.083728      0.279512   
4             43              6     -0.112552      0.012989      0.091491   

   1_qrs_morph3  1_qrs_morph4  
0      0.101373     -0.183387  
1      0.217544     -0.068248  
2      0.204400      0.335172  
3      0.526785      0.450969  
4      0.134004      0.265232  

[5 rows x 34 columns]

In [ ]:
x_data = data_df.iloc[:, 2:]
y_label = data_df[['type']]

In [ ]:
x_data.head()

0_pre-RR  0_post-RR   0_pPeak   0_tPeak   0_rPeak   0_sPeak   0_qPeak  \
0       163        165  0.069610 -0.083281  0.614133 -0.392761  0.047159   
1       165        166 -0.097030  0.597254 -0.078704 -0.078704 -0.137781   
2       166        102  0.109399  0.680528 -0.010649 -0.010649 -0.720620   
3       102        231  0.176376  0.256431 -0.101098 -0.707525 -0.101098   
4       231        165  0.585577  0.607461 -0.083499 -0.083499 -0.167858   

   0_qrs_interval  0_pq_interval  0_qt_interval  ...   1_qPeak  \
0              15              2             27  ... -0.023370   
1               3              5             14  ...  0.081637   
2               6             25             35  ... -0.148539   
3               4              3             14  ...  0.046898   
4               3             34             43  ... -0.112552   

   1_qrs_interval  1_pq_interval  1_qt_interval  1_st_interval  1_qrs_morph0  \
0              14              3             23              6     -0.023370   
1              15              5             27              7      0.081637   
2              33             13             52              6     -0.148539   
3              21              9             34              4      0.046898   
4              32              5             43              6     -0.112552   

   1_qrs_morph1  1_qrs_morph2  1_qrs_morph3  1_qrs_morph4  
0     -0.011650      0.082608      0.101373     -0.183387  
1      0.102992      0.191225      0.217544     -0.068248  
2     -0.060620      0.081080      0.204400      0.335172  
3      0.083728      0.279512      0.526785      0.450969  
4      0.012989      0.091491      0.134004      0.265232  

[5 rows x 32 columns]

In [ ]:
y_label.value_counts()

type
N       19880
VEB      1450
SVEB      133
F          26
Q           1
dtype: int64

In [ ]:

y_label.replace(['VEB', 'SVEB', 'F', 'Q'], 'arrhythmia', inplace=True)
y_label.replace(['N'], 'normal', inplace=True)

<ipython-input-7-3bae4833962a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_label.replace(['VEB', 'SVEB', 'F', 'Q'], 'arrhythmia', inplace=True)
<ipython-input-7-3bae4833962a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_label.replace(['N'], 'normal', inplace=True)


In [ ]:
y_label.value_counts()

type      
normal        19880
arrhythmia     1610
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_data, y_label, random_state=101)

In [ ]:
from sklearn.impute import SimpleImputer

column_names = X_train.columns
imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_train = pd.DataFrame(X_train, columns=column_names)

In [ ]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_train_scaled = min_max_scaler.fit_transform(X_train)
X_test_scaled = min_max_scaler.transform(X_test)

print(min_max_scaler.scale_)

[0.00239234 0.00286533 0.33861164 0.36676123 0.25442127 0.28228603
 0.24959481 0.01515152 0.01515152 0.00662252 0.01315789 0.24959481
 0.24529428 0.22899286 0.23751038 0.26042073 0.00239234 0.00286533
 0.16379205 0.65549799 0.27714266 0.25585831 0.36471832 0.00840336
 0.01234568 0.00529101 0.01492537 0.36471832 0.35326289 0.28819788
 0.26133471 0.21806155]


In [ ]:
X_train_scaled

array([[0.26794258, 0.32091691, 0.27413891, ..., 0.81155037, 0.81294658,
        0.66562644],
       [0.18421053, 0.22063037, 0.31534702, ..., 0.61126171, 0.59875189,
        0.51237786],
       [0.24401914, 0.28080229, 0.28656171, ..., 0.63641806, 0.63427856,
        0.54848729],
       ...,
       [0.5215311 , 0.59598854, 0.29285773, ..., 0.56673449, 0.60232537,
        0.51902972],
       [0.5215311 , 0.63037249, 0.25527957, ..., 0.62432224, 0.61558804,
        0.52858295],
       [0.24401914, 0.29512894, 0.28323495, ..., 0.62275286, 0.60982952,
        0.52155831]])

**Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=101, n_estimators=150)
model.fit(X_train_scaled,  y_train.to_numpy().reshape(-1))

RandomForestClassifier(n_estimators=150, random_state=101)

In [ ]:
from sklearn import metrics
y_pred = model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9966499162479062
*** Confusion Matrix ***
[[ 421   15]
 [   3 4934]]


**Gradient Boosting Classifier**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

modelg = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, random_state=0)
modelg.fit(X_train_scaled,  y_train.to_numpy().reshape(-1))

GradientBoostingClassifier(learning_rate=1.0, random_state=0)

In [ ]:
from sklearn import metrics
y_pred = modelg.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9923692536757863
*** Confusion Matrix ***
[[ 415   21]
 [  20 4917]]


**Decision Tree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=101)
dt_model.fit(X_train_scaled, y_train.to_numpy().reshape(-1))


DecisionTreeClassifier(random_state=101)

In [ ]:
from sklearn import metrics
y_pred = dt_model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.991252559091755
*** Confusion Matrix ***
[[ 411   25]
 [  22 4915]]


**Support Vector Machine Classifier**

In [ ]:
from sklearn.svm import SVC

svm_model = SVC(random_state=101)
svm_model.fit(X_train_scaled, y_train.to_numpy().reshape(-1))


SVC(random_state=101)

In [ ]:
from sklearn import metrics
y_pred = svm_model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9886469383956821
*** Confusion Matrix ***
[[ 389   47]
 [  14 4923]]


**K Neighbors Classifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train_scaled, y_train.to_numpy().reshape(-1))


KNeighborsClassifier()

In [ ]:
from sklearn import metrics
y_pred = knn_model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9944165270798436
*** Confusion Matrix ***
[[ 409   27]
 [   3 4934]]


**MLP Classifier**

In [ ]:
from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(random_state=101)
mlp_model.fit(X_train_scaled, y_train.to_numpy().reshape(-1))


MLPClassifier(random_state=101)

In [ ]:
from sklearn import metrics
y_pred = mlp_model.predict(X_test_scaled)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("*** Confusion Matrix ***")
print(metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.9946026428438489
*** Confusion Matrix ***
[[ 411   25]
 [   4 4933]]
